Core
Varkh/CashMachine-JS-Emulator pull request #20
Opened 2016-11-26 12:04 UTC by kds1660

2016-11-26 13:27 UTC, Varkh requested changes

2016-11-26 13:27 UTC, Varkh commented on index.html
> -
Remove change from this file. You are creating block.

2016-11-26 13:27 UTC, Varkh commented on js/controller/core.js
> +    this.pin='';
Don't create public variables

2016-11-26 13:27 UTC, Varkh commented on js/controller/core.js
> -        console.log("Enter pin");
Pleas don't remove console.log for now. It will help with testing

2016-11-26 13:27 UTC, Varkh commented on js/controller/core.js
> +    this.checkCardDate = function () {
This logic will be in CardModule. Remove

2016-11-27 06:35 UTC, kds1660 commented
а как мне откатить коммиты, реверт последнего опять затронет index.html,
git reset? боюсь напартачить


2016-11-26 15:27 GMT+02:00 Denys <notifications@github.com>:

> *@Varkh* requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/Varkh/CashMachine-JS-Emulator/pull/20#pullrequestreview-10214603>
> :
>
> > @@ -7,7 +7,6 @@
>      <link rel="stylesheet" href="css/main.css">
>
>      <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
> -
>
> Remove change from this file. You are creating block.
> ------------------------------
>
> In js/controller/core.js
> <https://github.com/Varkh/CashMachine-JS-Emulator/pull/20#pullrequestreview-10214603>
> :
>
> > @@ -6,17 +6,71 @@
>   * @constructor
>   */
>  function Core(cashModule, cardModule) {
> -    console.log("Waiting for card");
> +    this.pin='';
>
> Don't create public variables
> ------------------------------
>
> In js/controller/core.js
> <https://github.com/Varkh/CashMachine-JS-Emulator/pull/20#pullrequestreview-10214603>
> :
>
> >
>      this.pushCard = function (cardData) {
> -        console.log("Enter pin");
>
> Pleas don't remove console.log for now. It will help with testing
> ------------------------------
>
> In js/controller/core.js
> <https://github.com/Varkh/CashMachine-JS-Emulator/pull/20#pullrequestreview-10214603>
> :
>
> >      };
>
> -    this.enterPin = function (pin) {
> -        console.log("Autorized.")
> +    this.checkCardDate = function () {
>
> This logic will be in CardModule. Remove
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Varkh/CashMachine-JS-Emulator/pull/20#pullrequestreview-10214603>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AV8voEL26FlqplZx1zBvWMjwnf4SeG7dks5rCDO9gaJpZM4K84R5>
> .
>

2016-11-27 06:55 UTC, kds1660 commented
вроде реверт сделал все, тогда следующим коммитом сделать переписанное соре
и потом можно пуллреквестить

>
>

2016-11-28 09:00 UTC, Varkh approved these changes

2016-11-28 09:00 UTC, Varkh commented on js/controller/core.js
> +        if (isNumeric(button.value)) {
я так понимаю должно быть `$.isNumeric`

2016-11-28 09:00 UTC, merged