function getCash
Varkh/CashMachine-JS-Emulator pull request #25
Opened 2016-11-26 13:29 UTC by 00Programmer00

2016-11-27 09:04 UTC, Varkh requested changes

2016-11-27 09:04 UTC, Varkh commented on js/controller/cashModule.js
> +             console.log("Sorry but ATM have only 4250");
`throw new NotEnoughMoneyError`
Тобі треба створити цей еррор

2016-11-27 09:04 UTC, Varkh commented on js/controller/cashModule.js
> +var newCash = new CashModule();
remove this

2016-11-27 09:07 UTC, Varkh commented
Issue: #6

2016-11-29 19:56 UTC, closed without merging

2016-11-29 19:58 UTC, 00Programmer00 commented
Привіт, вибач, але я не можу розібратися з Error, та try catch.
Зможеш якось більш детально пояснити?

On 29 November 2016 at 21:56, Denys <notifications@github.com> wrote:

> Closed #25 <https://github.com/Varkh/CashMachine-JS-Emulator/pull/25>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Varkh/CashMachine-JS-Emulator/pull/25#event-875814166>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWATgDF6-NnEe34298e8x1Y0muUx5PIEks5rDINggaJpZM4K85Rw>
> .
>

2016-11-29 20:28 UTC, Varkh commented on js/controller/cashModule.js
> +             console.log("Sorry but ATM have only 4250");
@00Programmer00 
давай почнем з простого, заміни 
`console.log("Sorry but ATM have only 4250");`
на 
`throw new Error("Can't give cash. Not enough money.");`

P.S. Просто для загальної інформації, є функция console.error, подивись в чому різниця з console.log