Layout
Varkh/CashMachine-JS-Emulator pull request #55
Opened 2016-12-02 19:02 UTC by juliakukuliak

2016-12-03 09:57 UTC, Varkh requested changes

2016-12-03 09:57 UTC, Varkh commented on js/view/cardReaderView.js
> +							username: new CardDataModel("Name"),
`JSON.stringify(new CardDataModel(... parameters ...))`

2016-12-03 09:57 UTC, Varkh commented on js/model/cardDataModel.js
> +function CardDataModel(holderName) {
add more parameters:
`cardNumber`
`expirationDate`
`balance`
...

2016-12-03 09:58 UTC, Varkh commented
`This branch has conflicts that must be resolved`
Update changes from master

2016-12-06 08:14 UTC, Varkh requested changes

2016-12-06 08:14 UTC, Varkh commented on js/model/cardDataModel.js
> +// function CardDataModel(holderName, cardNumber, expirationDate, balance) {
Remove all commented code

2016-12-06 08:18 UTC, Varkh commented
@juliakukuliak
Tests are not passing.
Update in `coreTest.js` creation of `new CardDataModel()`

2016-12-06 08:20 UTC, juliakukuliak commented
coreTest должен принимать параметры, которые у нас в details в ивенте,
правильно?
06.12.2016 10:18 пользователь "Denys" <notifications@github.com> написал:

> @juliakukuliak <https://github.com/juliakukuliak>
> Tests are not passing.
> Update in coreTest.js creation of new CardDataModel()
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Varkh/CashMachine-JS-Emulator/pull/55#issuecomment-265088296>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATkrLhZZB3Cz37qP4uhdW6bDJv8zhokjks5rFRpdgaJpZM4LC4Nj>
> .
>

2016-12-06 08:34 UTC, Varkh commented
Передавай в CardDataModel в тесте параметры. Можешь те же что и во view

2016-12-06 21:11 UTC, kds1660 commented
только если мой пулреквест смерджится, там тоже уже изменения в тестах из-за ввода промежуточного состояния

2016-12-06 22:58 UTC, kds1660 commented
хотя подождем, что Денис скажет, можно конфликт и решить с файлом потом

2016-12-07 08:38 UTC, Varkh approved these changes

2016-12-07 08:38 UTC, merged