Core
Varkh/CashMachine-JS-Emulator pull request #64
Opened 2016-12-05 19:19 UTC by kds1660

1) add menu in at, after pin entered
2)add cash controller for adding nominals for cash view
3) add in cashModule method - return nominals in module for menu
4) add new state - state menu between enterPin and EnterSum

2016-12-06 08:22 UTC, Varkh commented
Nice

2016-12-07 08:39 UTC, Varkh commented on js/controller/core.js
> +                navigation.createMenu(['','','','View balanse',cashModule.getNominals()[0],cashModule.getNominals()[1],'Enter Cash','Back',],0)
I think it would be more readable in object form:
```
navigation.createMenu({
   4: 'View balanse',
   5: cashModule.getNominals()[0],
   6: cashModule.getNominals()[1],
   7: 'Enter Cash',
   8: 'Back'
})
```

You can create method that can handle both, array and object

2016-12-07 08:39 UTC, Varkh commented on js/controller/core.js
> +                        }, 1000);
1) move all numbers to constants
2) Increase to 2500

2016-12-07 08:40 UTC, Varkh requested changes
See comments

2016-12-07 09:31 UTC, Varkh approved these changes

2016-12-07 09:31 UTC, merged

2016-12-07 15:28 UTC, Varkh reviewed
Refactor

2016-12-07 15:28 UTC, Varkh commented on js/view/displayView.js
> +		for (var i=0;i<4;i++) {
This is jQuery, no need for `for`

2016-12-07 15:28 UTC, Varkh commented on js/view/displayView.js
> +			tr.css('height','30px');
Move to css

2016-12-07 15:28 UTC, Varkh commented on js/view/displayView.js
> +		table.css('width','100%');
To css

2016-12-07 15:28 UTC, Varkh commented on js/view/displayView.js
> +		for (var i=0;i<4;i++) {
Use jQuery

2016-12-07 15:28 UTC, Varkh commented on js/view/displayView.js
> +				table.find('td:even').eq(i).text(val[i+1]);
Use css

2016-12-07 16:21 UTC, kds1660 commented on js/view/displayView.js
> +		for (var i=0;i<4;i++) {
'for' for select value[i] element

2016-12-07 16:32 UTC, kds1660 commented on js/view/displayView.js
> +		for (var i=0;i<4;i++) {
maybe understand, change